$RepoPath = "F:\web\AllThings\_projects\n8n-ops.git"
$TreesPath = "F:\web\AllThings\_projects\n8n-ops-trees"

# Port mapping
$PortMap = @{
    "main" = @{ Frontend = 3000; Backend = 4000 }
    "f1"   = @{ Frontend = 3001; Backend = 4001 }
    "f2"   = @{ Frontend = 3002; Backend = 4002 }
    "f3"   = @{ Frontend = 3003; Backend = 4003 }
    "f4"   = @{ Frontend = 3004; Backend = 4004 }
}

function Show-Menu {
    Clear-Host
    Write-Host ""
    Write-Host "  n8n-ops Feature Manager" -ForegroundColor Cyan
    Write-Host "  =======================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  START (create/open Claude Code)" -ForegroundColor Green
    Write-Host "    1  Start f1  (localhost:3001 / 4001)"
    Write-Host "    2  Start f2  (localhost:3002 / 4002)"
    Write-Host "    3  Start f3  (localhost:3003 / 4003)"
    Write-Host "    4  Start f4  (localhost:3004 / 4004)"
    Write-Host ""
    Write-Host "  FINISH (commit, merge, cleanup)" -ForegroundColor Yellow
    Write-Host "    5  Finish f1"
    Write-Host "    6  Finish f2"
    Write-Host "    7  Finish f3"
    Write-Host "    8  Finish f4"
    Write-Host ""
    Write-Host "  OTHER" -ForegroundColor Magenta
    Write-Host "    L  List worktrees"
    Write-Host "    M  Open main (localhost:3000 / 4000)"
    Write-Host "    Q  Quit"
    Write-Host ""
}

function Start-Feature {
    param([string]$FeatureName)
    
    $FeaturePath = "$TreesPath\$FeatureName"
    $FrontendPort = $PortMap[$FeatureName].Frontend
    $BackendPort = $PortMap[$FeatureName].Backend

    # Build the startup message that will show in the new window
    $StartupMessage = @"
Write-Host ''
Write-Host '  =======================================' -ForegroundColor Cyan
Write-Host '  $FeatureName - n8n-ops' -ForegroundColor Cyan
Write-Host '  =======================================' -ForegroundColor Cyan
Write-Host ''
Write-Host '  Frontend: http://localhost:$FrontendPort' -ForegroundColor Green
Write-Host '  Backend:  http://localhost:$BackendPort' -ForegroundColor Green
Write-Host ''
Write-Host '  .env.local has these ports configured' -ForegroundColor Gray
Write-Host ''
claude --dangerously-skip-permissions
"@

    # Check if worktree already exists
    if (Test-Path $FeaturePath) {
        Write-Host "Worktree '$FeatureName' exists. Opening Claude Code..." -ForegroundColor Cyan
        Start-Process powershell -ArgumentList "-NoExit", "-Command", "cd '$FeaturePath'; $StartupMessage"
        return
    }

    # Create the worktree
    Push-Location $RepoPath
    git fetch origin
    git worktree add $FeaturePath -b $FeatureName
    Pop-Location

    if ($LASTEXITCODE -eq 0) {
        # Create .env file with ports
        $envContent = @"
# Auto-generated by n8n-ops launcher
FEATURE_NAME=$FeatureName
FRONTEND_PORT=$FrontendPort
BACKEND_PORT=$BackendPort
PORT=$FrontendPort
API_PORT=$BackendPort
VITE_PORT=$FrontendPort
"@
        $envContent | Out-File -FilePath "$FeaturePath\.env.local" -Encoding UTF8
        
        Write-Host "Created worktree '$FeatureName'" -ForegroundColor Green
        Write-Host "Location: $FeaturePath" -ForegroundColor Cyan
        Write-Host "Opening Claude Code..." -ForegroundColor Cyan
        
        Start-Process powershell -ArgumentList "-NoExit", "-Command", "cd '$FeaturePath'; $StartupMessage"
    } else {
        Write-Host "Failed to create worktree" -ForegroundColor Red
    }
}

function Finish-Feature {
    param([string]$FeatureName)
    
    $FeaturePath = "$TreesPath\$FeatureName"
    $MainPath = "$TreesPath\main"

    # Verify worktree exists
    if (-not (Test-Path $FeaturePath)) {
        Write-Host "Worktree '$FeatureName' not found" -ForegroundColor Red
        return
    }

    # Prompt for commit message
    Write-Host ""
    Write-Host "Enter commit message (or press Enter for default): " -NoNewline -ForegroundColor White
    $CommitMessage = Read-Host
    if ([string]::IsNullOrEmpty($CommitMessage)) {
        $CommitMessage = "Complete feature: $FeatureName"
    }

    # Step 1: Commit any pending changes
    Write-Host "`n[1/5] Checking for uncommitted changes..." -ForegroundColor Cyan
    Push-Location $FeaturePath
    $status = git status --porcelain
    if ($status) {
        Write-Host "Committing pending changes..." -ForegroundColor Yellow
        git add .
        git commit -m $CommitMessage
    } else {
        Write-Host "No pending changes" -ForegroundColor Gray
    }

    # Step 2: Push feature branch
    Write-Host "`n[2/5] Pushing feature branch..." -ForegroundColor Cyan
    git push -u origin $FeatureName 2>$null
    Pop-Location

    # Step 3: Merge to main
    Write-Host "`n[3/5] Merging to main..." -ForegroundColor Cyan
    Push-Location $MainPath
    git pull
    git merge $FeatureName -m "Merge feature: $FeatureName"

    if ($LASTEXITCODE -ne 0) {
        Write-Host "`nMerge conflict detected!" -ForegroundColor Red
        Write-Host "Resolve conflicts in: $MainPath" -ForegroundColor Yellow
        Write-Host "Then commit and run finish again" -ForegroundColor Yellow
        Pop-Location
        return
    }

    git push
    Pop-Location

    # Step 4: Remove worktree and branches
    Write-Host "`n[4/5] Removing worktree and branches..." -ForegroundColor Cyan
    Push-Location $RepoPath
    git worktree remove $FeaturePath --force
    git branch -d $FeatureName 2>$null
    git push origin --delete $FeatureName 2>$null
    git worktree prune
    Pop-Location

    # Step 5: Done
    Write-Host "`n[5/5] Complete!" -ForegroundColor Green
    Write-Host "Feature '$FeatureName' merged and cleaned up." -ForegroundColor Green
}

function List-Worktrees {
    Write-Host ""
    Write-Host "Active Worktrees:" -ForegroundColor Cyan
    Write-Host "=================" -ForegroundColor Cyan
    Push-Location $RepoPath
    git worktree list
    Pop-Location
}

# Main loop
do {
    Show-Menu
    Write-Host "  Choice: " -NoNewline -ForegroundColor White
    $choice = Read-Host

    switch ($choice.ToUpper()) {
        "1" { Start-Feature "f1"; pause }
        "2" { Start-Feature "f2"; pause }
        "3" { Start-Feature "f3"; pause }
        "4" { Start-Feature "f4"; pause }
        "5" { Finish-Feature "f1"; pause }
        "6" { Finish-Feature "f2"; pause }
        "7" { Finish-Feature "f3"; pause }
        "8" { Finish-Feature "f4"; pause }
        "L" { List-Worktrees; pause }
        "M" { Start-Feature "main"; pause }
        "Q" { exit }
        default { Write-Host "Invalid choice" -ForegroundColor Red; Start-Sleep -Seconds 1 }
    }
} while ($true)